# Generated by Django 5.0.6 on 2024-06-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(default=None, upload_to='uploads/'),
        ),
    ]
